name: Build on Pull Request Merge

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    
    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install
      
    - name: Build project
      run: npm run build
